#!/bin/bash

DOCKERFILE=Dockerfile
TAG_NAME=`echo $IMAGE_NAME | cut -d ':' -f 2`

if [[ "$TAG_NAME" == nightly* ]]; then
    cat $DOCKERFILE | sed "s/FROM jboss\/keycloak:.*/FROM jboss\/keycloak:$TAG_NAME/" > $DOCKERFILE.tmp
    DOCKERFILE=Dockerfile.tmp
fi

docker build -t $IMAGE_NAME -f $DOCKERFILE .

if [[ "$TAG_NAME" == nightly* ]]; then
    rm Dockerfile.tmp
fi
