#!/bin/bash

KEYCLOAK_VERSION=$1

sed -i "s/ENV KEYCLOAK_VERSION .*/ENV KEYCLOAK_VERSION $KEYCLOAK_VERSION/" server/Dockerfile
sed -i "s/ARG KEYCLOAK_VERSION=.*/ARG KEYCLOAK_VERSION=$KEYCLOAK_VERSION/" server-x/Dockerfile
