---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dev-volume
  namespace: keycloak
data:
  entrypoint-instead-of-dockerfile.sh: |
    #!/bin/bash
    set -e
    set -x

    # -bprivate=eth0 startup can't be used for inet-address -> nic
    sed -i 's|<inet-address value="${jboss.bind.address.private:127.0.0.1}"/>|<nic name="eth0"/>|' keycloak/standalone/configuration/standalone-ha.xml

    # Prepare xsl transoforms

    curl -o xsl-transform -sLS \
      https://raw.githubusercontent.com/Reposoft/keycloak-ha-kubernetes/keycloak3-ha-mysql/server-ha-mysql/xsl-transform.sh;
    chmod u+x xsl-transform

    echo '<?xml version="1.0" encoding="UTF-8"?><xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:output method="xml" indent="yes"/><xsl:template match="@*|node()"><xsl:copy><xsl:apply-templates select="@*|node()"/></xsl:copy></xsl:template></xsl:stylesheet>' > indent.xsl
    ./xsl-transform keycloak/standalone/configuration/standalone-ha.xml indent.xsl > /dev/null

    # CACHE_OWNERS

    curl -o cache-owners.xsl -sLS \
      https://raw.githubusercontent.com/Reposoft/keycloak-ha-kubernetes/keycloak3-ha-mysql/server-ha-mysql/cache-owners.xsl;
    ./xsl-transform keycloak/standalone/configuration/standalone-ha.xml cache-owners.xsl

    # Add node identifier placeholder

    curl -o node-identifier.xsl -sLS \
      https://raw.githubusercontent.com/Reposoft/keycloak-ha-kubernetes/keycloak3-ha-mysql/server-ha-mysql/node-identifier.xsl;
    sed -i 's|transactions:3.0|transactions:4.0|' node-identifier.xsl
    ./xsl-transform keycloak/standalone/configuration/standalone-ha.xml node-identifier.xsl

    # JGROUPS_STACK with tcp=JDBC_PING

    if [ "$JGROUPS_STACK" == "tcp" ]; then
      ./xsl-transform keycloak/standalone/configuration/standalone-ha.xml /keycloak-ha-dev/jgroups-stack-tcp.xsl
    fi
    ./xsl-transform keycloak/standalone/configuration/standalone-ha.xml /keycloak-ha-dev/jgroups-jdbc.xsl

    # End custom entrypoint

    echo "Calling the actual entrypoint ..."
    echo ""
    exec "$@"
  jgroups-stack-tcp.xsl: |
    <?xml version="1.0" encoding="UTF-8"?>

    <xsl:stylesheet version="2.0"
                    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                    xmlns:jgroups="urn:jboss:domain:jgroups:5.0"
                    exclude-result-prefixes="jgroups">

        <xsl:output method="xml" indent="yes"/>

        <xsl:template match="//jgroups:subsystem/jgroups:channels/jgroups:channel">
            <xsl:copy>
                <xsl:apply-templates select="node()|@*"/>
                <xsl:attribute name="stack">tcp</xsl:attribute>
            </xsl:copy>
        </xsl:template>

        <xsl:template match="@*|node()">
            <xsl:copy>
                <xsl:apply-templates select="@*|node()"/>
            </xsl:copy>
        </xsl:template>

    </xsl:stylesheet>
  jgroups-jdbc.xsl: |
    <?xml version="1.0" encoding="UTF-8"?>

    <xsl:stylesheet version="2.0"
                    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                    xmlns:jgroups="urn:jboss:domain:jgroups:5.0"
                    exclude-result-prefixes="jgroups">

        <xsl:output method="xml" indent="yes"/>

        <xsl:template match="//jgroups:subsystem/jgroups:stacks/jgroups:stack[@name='tcp']/jgroups:socket-protocol[@type='MPING']">
            <xsl:comment> MPING was removed in favor of JDBC_PING </xsl:comment>
            <protocol xmlns="urn:jboss:domain:jgroups:5.0" type="JDBC_PING">
                <property name="datasource_jndi_name">java:jboss/datasources/KeycloakDS</property>
            </protocol>
        </xsl:template>

        <xsl:template match="@*|node()">
            <xsl:copy>
                <xsl:apply-templates select="@*|node()"/>
            </xsl:copy>
        </xsl:template>

    </xsl:stylesheet>
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kc
  namespace: keycloak
spec:
  replicas: 2
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak-ha
        image: jboss/keycloak:3.4.0.CR1@sha256:374cdff2b6b2f47770044b700120424e949d140603bc496af83117f7ac3c151a
        env:
        - name: MYSQL_PORT_3306_TCP_ADDR
          value: mysql.mysql
        - name: MYSQL_PORT_3306_TCP_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: keycloak
        - name: MYSQL_USER
          value: keycloak
        - name: MYSQL_PASSWORD
          value: keycloak
        # first start only, testing only
        - name: KEYCLOAK_USER
          value: admin
        - name: KEYCLOAK_PASSWORD
          value: test
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: CACHE_OWNERS
          value: "2"
        - name: JGROUPS_STACK
          value: tcp
        command:
        - /bin/bash
        - /keycloak-ha-dev/entrypoint-instead-of-dockerfile.sh
        - /opt/jboss/docker-entrypoint.sh
        #args:
        - -b=0.0.0.0
        - -bmanagement=0.0.0.0
        - --server-config=standalone-ha.xml
        ports:
        - name: http
          containerPort: 8080
        - name: management
          containerPort: 9090
        - name: jgroups-tcp
          containerPort: 7600
        - name: jgroups-tcp-fd
          containerPort: 57600
        - name: jgroups-udp
          containerPort: 55200
          protocol: UDP
        - name: jgroups-udp-mc
          containerPort: 45688
          protocol: UDP
        - name: jgroups-udp-fd
          containerPort: 54200
          protocol: UDP
        - name: modcluster
          containerPort: 23364
        - name: modcluster-udp
          containerPort: 23364
          protocol: UDP
        - name: txn-recovery-ev
          containerPort: 4712
        - name: txn-status-mgr
          containerPort: 4713
        readinessProbe:
          httpGet:
            path: /auth/
            port: 8080
        volumeMounts:
        - name: keycloak-ha-dev
          mountPath: /keycloak-ha-dev
      volumes:
      - name: keycloak-ha-dev
        configMap:
          name: dev-volume
