export const INIT_CHANNEL = 'INIT_CHANNEL';
export const CHANNEL_SUCCESS = 'CHANNEL_SUCCESS';
export const CHANNEL_ERROR = 'CHANNEL_ERROR';
export const SEND_COMMAND = 'SEND_COMMAND';
export const RECEIVED_DATA = 'RECEIVED_DATA';
export const CHANNEL_CLOSED = 'CHANNEL_CLOSED';
