version: '3'

volumes:
  oracle_data:
    driver: local

services:
  oracle:
    image: carloscastillo/rgt-oracle-xe-11g
    volumes:
      - oracle_data:/var/lib/oracle/data
    ports:
      - 1521:1521
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: ORACLE
      DB_ADDR: oracle
      DB_PORT: 1521
      DB_DATABASE: XE
      DB_USER: SYSTEM
      DB_PASSWORD: oracle
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8080:8080
    volumes:
      # The host directory should contain the `ojdbc.jar` file.
      - ./jdbc:/opt/jboss/keycloak/modules/system/layers/base/com/oracle/jdbc/main/driver
    depends_on:
      - oracle
